# Generated by Django 5.1.6 on 2025-03-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dayofweek_appointment_doctoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='taking_dates',
            field=models.BooleanField(default=True),
        ),
    ]
