# Generated by Django 5.1.6 on 2025-04-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_doctor_taking_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ensurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ensurance_logos/')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='ensurances',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='api.ensurance'),
        ),
    ]
