# Generated by Django 5.1.6 on 2025-04-02 01:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ensurance_doctor_ensurances'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='virtual',
            field=models.BooleanField(default=False, help_text='Indicates if this is a virtual appointment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[api.models.validate_square_image]),
        ),
    ]
