# Generated by Django 5.1.6 on 2025-04-02 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_doctoravailability_virtual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.clinic'),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.specialty'),
        ),
    ]
