# Generated by Django 5.1.6 on 2025-04-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text="Doctor's sex (Male or Female)", max_length=1, null=True, blank=True),
            preserve_default=False,
        ),
    ]
