# Generated by Django 5.1.6 on 2025-04-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_doctor_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='takes_in_person',
            field=models.BooleanField(default=False, help_text='Doctor takes in-person appointments'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='takes_virtual',
            field=models.BooleanField(default=False, help_text='Doctor takes virtual appointments'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='taking_dates',
            field=models.BooleanField(default=False),
        ),
    ]
