# Generated by Django 5.1.6 on 2025-04-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_doctor_takes_in_person_doctor_takes_virtual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates if this availability is active'),
        ),
    ]
