# Generated by Django 5.1.6 on 2025-04-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_doctoravailability_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], help_text="Doctor's sex (Male or Female)", max_length=1, null=True),
        ),
    ]
