# Generated by Django 5.1.6 on 2025-04-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_clinic_city_clinic_location_clinic_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_doctors',
            field=models.ManyToManyField(blank=True, help_text='Doctors marked as favorites by the user', related_name='favorited_by', to='api.doctor'),
        ),
    ]
