# Generated by Django 5.1.6 on 2025-04-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_favorite_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.TextField(blank=True, help_text="Doctor's self-description", null=True),
        ),
    ]
