# Generated by Django 5.1.6 on 2025-05-20 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.JSONField(help_text="List of time slots (e.g., ['09:00', '10:00']) for the schedule.")),
                ('title', models.CharField(blank=True, help_text='Optional title for the schedule. Auto-generated if not provided.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the schedule was created.')),
                ('place', models.ForeignKey(blank=True, help_text='The clinic where the schedule is set. Null for virtual schedules.', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.clinic')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
