# Generated by Django 5.1.6 on 2025-05-21 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_schedule_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(help_text='Start date of the week (Monday).')),
                ('doctor', models.ForeignKey(help_text='Doctor associated with this week availability.', on_delete=django.db.models.deletion.CASCADE, related_name='week_availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Week Availability',
                'verbose_name_plural': 'Week Availabilities',
                'db_table': 'week_availability',
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Specific date of availability (e.g., Wednesday, May 21, 2025).')),
                ('hours', models.JSONField(help_text="List of available hours (e.g., ['09:00', '10:00']).")),
                ('place', models.ForeignKey(blank=True, help_text='Clinic for in-person appointments; null for virtual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekday_availabilities', to='api.clinic')),
                ('week_availability', models.ForeignKey(help_text='Week this day belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='weekdays', to='api.weekavailability')),
            ],
            options={
                'verbose_name': 'Week Day',
                'verbose_name_plural': 'Week Days',
                'db_table': 'week_day',
            },
        ),
    ]
