# Generated by Django 5.1.6 on 2025-05-28 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_weekavailability_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='days',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='specialization',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='DayOfWeek',
        ),
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
    ]
