# Generated by Django 5.1.6 on 2025-05-28 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_doctoravailability_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.JSONField()),
                ('appointment', models.ForeignKey(help_text='Schedule for the appointment.', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='api.weekday')),
                ('user', models.ForeignKey(help_text='User who booked the appointment.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
