# Generated by Django 5.1.6 on 2025-05-29 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user',
            new_name='patient',
        ),
    ]
