# Generated by Django 5.1.6 on 2025-05-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_user_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='active',
            field=models.BooleanField(default=True, help_text='Is the appointment active?'),
        ),
    ]
