# Generated by Django 5.1.6 on 2025-11-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True, help_text='Detailed review text', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='headline',
            field=models.CharField(blank=True, help_text='Short summary of the review', max_length=100, null=True),
        ),
    ]
