# Generated by Django 5.1.6 on 2025-12-08 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_review_body_alter_review_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment',
            field=models.ForeignKey(help_text='Schedule for the appointment.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.weekday'),
        ),
    ]
