# Generated by Django 5.1.6 on 2026-04-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_appointment_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text="Doctor's age", null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='name', help_text="Doctor's first name", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='last name', help_text="Doctor's last name", max_length=30),
            preserve_default=False,
        ),
    ]
