# Generated by Django 5.1.6 on 2026-05-08 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Pega aquí TODOS los RemoveField y DeleteModel que ya tienes
                migrations.RemoveField(model_name='appointment', name='appointment'),
                migrations.RemoveField(model_name='appointment', name='patient'),
                migrations.RemoveField(model_name='weekday', name='place'),
                migrations.RemoveField(model_name='schedule', name='place'),
                migrations.RemoveField(model_name='doctor', name='clinics'),
                migrations.RemoveField(model_name='doctor', name='ensurances'),
                migrations.RemoveField(model_name='doctor', name='specialties'),
                migrations.RemoveField(model_name='doctor', name='user'),
                migrations.RemoveField(model_name='user', name='favorite_doctors'),
                migrations.RemoveField(model_name='schedule', name='doctor'),
                migrations.RemoveField(model_name='doctordocument', name='doctor'),
                migrations.RemoveField(model_name='review', name='doctor'),
                migrations.DeleteModel(name='PasswordResetToken'),
                migrations.AlterUniqueTogether(name='review', unique_together=None),
                migrations.RemoveField(model_name='review', name='user'),
                migrations.RemoveField(model_name='user', name='groups'),
                migrations.RemoveField(model_name='user', name='user_permissions'),
                migrations.RemoveField(model_name='weekavailability', name='doctor'),
                migrations.RemoveField(model_name='weekday', name='week_availability'),
                migrations.DeleteModel(name='Appointment'),
                migrations.DeleteModel(name='Clinic'),
                migrations.DeleteModel(name='Ensurance'),
                migrations.DeleteModel(name='Specialty'),
                migrations.DeleteModel(name='Schedule'),
                migrations.DeleteModel(name='DoctorDocument'),
                migrations.DeleteModel(name='Doctor'),
                migrations.DeleteModel(name='Review'),
                migrations.DeleteModel(name='User'),
                migrations.DeleteModel(name='WeekAvailability'),
                migrations.DeleteModel(name='WeekDay'),
            ],
            database_operations=[],  # Crucial: Al estar vacío, NO borra nada en SQL
        ),
    ]