# Generated by Django 5.1.6 on 2026-05-09 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clinic',
            new_name='api_clinic_locatio_fcc240_idx',
            old_name='search_clin_locatio_65dbbc_idx',
        ),
        migrations.AlterModelTable(
            name='clinic',
            table='api_clinic',
        ),
        migrations.AlterModelTable(
            name='ensurance',
            table='api_ensurance',
        ),
        migrations.AlterModelTable(
            name='specialty',
            table='api_specialty',
        ),
    ]
