# Generated by Django 5.1.6 on 2026-05-11 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0002_rename_search_clin_locatio_65dbbc_idx_api_clinic_locatio_fcc240_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(help_text='Start date of the week (Monday).')),
            ],
            options={
                'db_table': 'week_availability',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.JSONField(help_text="List of time slots (e.g., ['09:00', '10:00']) for the schedule.")),
                ('title', models.CharField(blank=True, help_text='Optional title for the schedule. Auto-generated if not provided.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the schedule was created.')),
                ('place', models.ForeignKey(blank=True, help_text='The clinic where the schedule is set. Null for virtual schedules.', null=True, on_delete=django.db.models.deletion.CASCADE, to='search.clinic')),
            ],
            options={
                'db_table': 'api_schedule',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Specific date of availability (e.g., Wednesday, May 21, 2025).')),
                ('hours', models.JSONField(help_text="List of available hours (e.g., ['09:00', '10:00']).")),
                ('place', models.ForeignKey(blank=True, help_text='Clinic for in-person appointments; null for virtual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekday_availabilities', to='search.clinic')),
                ('week_availability', models.ForeignKey(help_text='Week this day belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='weekdays', to='appointments.weekavailability')),
            ],
            options={
                'verbose_name': 'Week Day',
                'verbose_name_plural': 'Week Days',
                'db_table': 'week_day',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.JSONField()),
                ('active', models.BooleanField(default=True, help_text='Is the appointment active?')),
                ('appointment', models.ForeignKey(help_text='Schedule for the appointment.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.weekday')),
            ],
            options={
                'db_table': 'api_appointment',
            },
        ),
    ]
