# Generated by Django 5.1.6 on 2026-05-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.JSONField()),
                ('active', models.BooleanField(default=True, help_text='Is the appointment active?')),
            ],
            options={
                'db_table': 'api_appointment',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.JSONField(help_text="List of time slots (e.g., ['09:00', '10:00']) for the schedule.")),
                ('title', models.CharField(blank=True, help_text='Optional title for the schedule. Auto-generated if not provided.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the schedule was created.')),
            ],
            options={
                'db_table': 'api_schedule',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeekAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(help_text='Start date of the week (Monday).')),
            ],
            options={
                'db_table': 'week_availability',
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Specific date of availability (e.g., Wednesday, May 21, 2025).')),
                ('hours', models.JSONField(help_text="List of available hours (e.g., ['09:00', '10:00']).")),
            ],
            options={
                'verbose_name': 'Week Day',
                'verbose_name_plural': 'Week Days',
                'db_table': 'week_day',
            },
        ),
    ]
