# Generated by Django 5.1.6 on 2026-05-12 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(help_text='User who booked the appointment.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(help_text='The doctor associated with this schedule.', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='place',
            field=models.ForeignKey(blank=True, help_text='The clinic where the schedule is set. Null for virtual schedules.', null=True, on_delete=django.db.models.deletion.CASCADE, to='search.clinic'),
        ),
        migrations.AddField(
            model_name='weekavailability',
            name='doctor',
            field=models.ForeignKey(help_text='Doctor associated with this week availability.', on_delete=django.db.models.deletion.CASCADE, related_name='week_availabilities', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='weekday',
            name='place',
            field=models.ForeignKey(blank=True, help_text='Clinic for in-person appointments; null for virtual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekday_availabilities', to='search.clinic'),
        ),
        migrations.AddField(
            model_name='weekday',
            name='week_availability',
            field=models.ForeignKey(help_text='Week this day belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='weekdays', to='appointments.weekavailability'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment',
            field=models.ForeignKey(help_text='Schedule for the appointment.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.weekday'),
        ),
    ]
