# Generated by Django 5.1.6 on 2026-05-11 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0002_doctor_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=24, help_text='User who booked the appointment.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(default=18, help_text='The doctor associated with this schedule.', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekavailability',
            name='doctor',
            field=models.ForeignKey(default=18, help_text='Doctor associated with this week availability.', on_delete=django.db.models.deletion.CASCADE, related_name='week_availabilities', to='doctors.doctor'),
            preserve_default=False,
        ),
    ]
