# Generated by Django 5.1.6 on 2026-05-11 22:31

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0002_rename_search_clin_locatio_65dbbc_idx_api_clinic_locatio_fcc240_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text="Doctor's self-description", null=True)),
                ('exequatur', models.CharField(max_length=20, unique=True)),
                ('experience', models.PositiveIntegerField(help_text='Years of Experience')),
                ('first_name', models.CharField(help_text="Doctor's first name", max_length=30)),
                ('last_name', models.CharField(help_text="Doctor's last name", max_length=30)),
                ('age', models.PositiveIntegerField(blank=True, help_text="Doctor's age", null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], help_text="Doctor's sex (Male or Female)", max_length=1, null=True)),
                ('taking_dates', models.BooleanField(default=False)),
                ('takes_virtual', models.BooleanField(default=False, help_text='Doctor takes virtual appointments')),
                ('takes_in_person', models.BooleanField(default=False, help_text='Doctor takes in-person appointments')),
                ('clinics', models.ManyToManyField(related_name='doctors', to='search.clinic')),
                ('ensurances', models.ManyToManyField(blank=True, related_name='doctors', to='search.ensurance')),
                ('specialties', models.ManyToManyField(related_name='doctors', to='search.specialty')),
            ],
            options={
                'db_table': 'api_doctor',
            },
        ),
        migrations.CreateModel(
            name='DoctorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='doctors.doctor')),
            ],
            options={
                'db_table': 'api_doctordocument',
            },
        ),
    ]
