# Generated by Django 5.1.6 on 2026-05-11 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('headline', models.CharField(blank=True, help_text='Short summary of the review.', max_length=100, null=True)),
                ('body', models.TextField(blank=True, help_text='Detailed review text.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.BooleanField(default=False, help_text='Indicates if this is a test review (not shown in public listings).')),
            ],
            options={
                'db_table': 'api_review',
            },
        ),
    ]
